# Generated by Django 5.1.15 on 2026-03-31 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "plan",
                    models.CharField(choices=[("basis", "Basis"), ("extra", "Extra")], default="basis", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Aktiv"), ("paused", "Pausiert"), ("cancelled", "Gekündigt")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateField()),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monatlich"), ("yearly", "Jährlich")], default="monthly", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        limit_choices_to={"role": "owner"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
