# Generated by Django 5.1.15 on 2026-03-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_phone_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="availability",
            field=models.JSONField(blank=True, default=dict, help_text="Inspector schedule data"),
        ),
    ]
