# Generated by Django 5.1.15 on 2026-04-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_emailverificationtoken_onboardingprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[("basis", "Basis"), ("standard", "Standard"), ("premium", "Premium")],
                default="basis",
                max_length=20,
            ),
        ),
    ]
