# Generated by Django 5.1.15 on 2026-04-01 14:19

from django.db import migrations


def rename_extra_to_standard(apps, schema_editor):
    Subscription = apps.get_model("accounts", "Subscription")
    Subscription.objects.filter(plan="extra").update(plan="standard")


def rename_standard_to_extra(apps, schema_editor):
    Subscription = apps.get_model("accounts", "Subscription")
    Subscription.objects.filter(plan="standard").update(plan="extra")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_subscription_plan"),
    ]

    operations = [
        migrations.RunPython(rename_extra_to_standard, rename_standard_to_extra),
    ]
