# Generated by Django 5.1.15 on 2026-04-02 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_rename_extra_to_standard"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, help_text="Soft-delete timestamp (30-day grace period)", null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="privacy_consent_at",
            field=models.DateTimeField(blank=True, help_text="DSGVO privacy consent timestamp", null=True),
        ),
        migrations.CreateModel(
            name="DataExportRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ausstehend"),
                            ("PROCESSING", "In Bearbeitung"),
                            ("COMPLETED", "Abgeschlossen"),
                            ("FAILED", "Fehlgeschlagen"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("export_file", models.FileField(blank=True, upload_to="exports/%Y/%m/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_export_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
    ]
