# Generated by Django 5.1.15 on 2026-03-31 17:08

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.CharField(max_length=255)),
                (
                    "access_method",
                    models.CharField(
                        choices=[
                            ("key_handover", "Schlüsselübergabe"),
                            ("lockbox", "Schlüsselbox"),
                            ("smart_lock", "Smart Lock"),
                        ],
                        default="key_handover",
                        max_length=20,
                    ),
                ),
                ("access_notes", encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ("special_instructions", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Aktiv"), ("paused", "Pausiert"), ("archived", "Archiviert")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        limit_choices_to={"role": "owner"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("items", models.JSONField(default=list, help_text="Array of {category, label, type} objects")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "apartment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_template",
                        to="apartments.apartment",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="apartment",
            index=models.Index(fields=["owner", "status"], name="apartments__owner_i_bbab10_idx"),
        ),
    ]
