# Generated by Django 5.1.15 on 2026-03-31 18:34

from django.db import migrations, models

import apps.apartments.models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklisttemplate",
            name="items",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of {category, label, allowed_results, order} objects",
                validators=[apps.apartments.models.validate_checklist_items],
            ),
        ),
    ]
