# Generated by Django 5.1.15 on 2026-04-01 07:37

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0002_alter_checklisttemplate_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="access_code",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="Lockbox PIN or smart lock code"
            ),
        ),
    ]
