# Generated by Django 5.1.15 on 2026-04-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0003_apartment_access_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="city",
            field=models.CharField(blank=True, default="Wien", max_length=100),
        ),
        migrations.AddField(
            model_name="apartment",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="apartment",
            name="street",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="apartment",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
