# Generated by Django 5.1.15 on 2026-03-31 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apartments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scheduled_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Geplant"),
                            ("in_progress", "Laufend"),
                            ("completed", "Abgeschlossen"),
                            ("cancelled", "Storniert"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "overall_rating",
                    models.CharField(
                        blank=True,
                        choices=[("ok", "OK"), ("attention", "Achtung"), ("urgent", "Dringend")],
                        max_length=20,
                    ),
                ),
                ("general_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="apartments.apartment",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        limit_choices_to={"role": "inspector"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectionItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checklist_label", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                (
                    "result",
                    models.CharField(
                        choices=[("ok", "OK"), ("flagged", "Auffällig"), ("na", "N/A")], default="ok", max_length=20
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("none", "Keine"),
                            ("low", "Niedrig"),
                            ("medium", "Mittel"),
                            ("high", "Hoch"),
                            ("urgent", "Dringend"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="inspections.inspection"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.ImageField(upload_to="photos/%Y/%m/")),
                ("thumbnail", models.ImageField(blank=True, upload_to="photos/thumbs/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="inspections.inspection"
                    ),
                ),
                (
                    "inspection_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="inspections.inspectionitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["apartment", "status"], name="inspections_apartme_290b6c_idx"),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["inspector", "scheduled_at"], name="inspections_inspect_058548_idx"),
        ),
        migrations.AddIndex(
            model_name="inspectionitem",
            index=models.Index(fields=["inspection", "result"], name="inspections_inspect_39271f_idx"),
        ),
    ]
