# Generated by Django 5.1.15 on 2026-03-31 21:26

from django.db import migrations, models

import baky.storage


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.ImageField(
                upload_to=baky.storage.generate_upload_path, validators=[baky.storage.validate_photo_file]
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to=baky.storage.generate_thumbnail_path),
        ),
    ]
