# Generated by Django 5.1.15 on 2026-04-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0002_alter_photo_file_alter_photo_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="scheduled_end",
            field=models.DateTimeField(
                blank=True, help_text="Ende der geplanten Inspektion. Mindestens 2 Stunden nach Beginn.", null=True
            ),
        ),
    ]
