# Generated by Django 5.1.15 on 2026-04-02 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0003_inspection_scheduled_end"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="time_slot",
            field=models.CharField(
                blank=True,
                choices=[
                    ("morning", "Vormittag (08:00–10:30)"),
                    ("midday", "Mittag (10:30–13:00)"),
                    ("afternoon", "Nachmittag (13:30–16:00)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="inspector",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "inspector"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inspections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
