# Generated by Django 5.1.15 on 2026-04-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0004_inspection_time_slot_alter_inspection_inspector"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="flagged_at",
            field=models.DateTimeField(blank=True, help_text="When the photo was flagged/unflagged", null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="is_flagged",
            field=models.BooleanField(default=False, help_text="Owner-flagged for retention beyond 90 days"),
        ),
    ]
