# Generated by Django 5.1.15 on 2026-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0006_add_global_slot_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, help_text="Zeitpunkt der Stornierung.", null=True),
        ),
        migrations.AddField(
            model_name="inspection",
            name="late_cancellation",
            field=models.BooleanField(
                default=False, help_text="True wenn Stornierung weniger als 24h vor dem Termin erfolgte."
            ),
        ),
    ]
