# Generated by Django 5.1.15 on 2026-04-01 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inspections", "0003_inspection_scheduled_end"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("generating", "Wird erstellt"),
                            ("completed", "Fertig"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("html_content", models.TextField(blank=True, help_text="Rendered HTML report content")),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "inspection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="report", to="inspections.inspection"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["inspection", "status"], name="reports_rep_inspect_69e9b5_idx")],
            },
        ),
    ]
