# Generated by Django 5.1.15 on 2026-04-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, help_text="When the report email was sent to the owner", null=True),
        ),
    ]
